- job:
    name: gcorecloud-unittest
    parent: golang-test
    description: |
      Run gcorecloud unit test
    run: .zuul/playbooks/gcorecloud-unittest/run.yaml
    nodeset: ubuntu-xenial-ut

- job:
    name: gcorecloud-acceptance-test
    parent: golang-test
    description: |
      Run gcorecloud acceptance test on master branch
    run: .zuul/playbooks/gcorecloud-acceptance-test/run.yaml
    nodeset: ubuntu-bionic

- job:
    name: gcorecloud-acceptance-test-ironic
    parent: golang-test
    description: |
      Run gcorecloud ironic acceptance test on master branch
    run: .zuul/playbooks/gcorecloud-acceptance-test-ironic/run.yaml
    nodeset: ubuntu-bionic

- job:
    name: gcorecloud-acceptance-test-stein
    parent: gcorecloud-acceptance-test
    description: |
      Run gcorecloud acceptance test on stein branch
    vars:
      global_env:
        OS_BRANCH: stable/stein

- job:
    name: gcorecloud-acceptance-test-rocky
    parent: gcorecloud-acceptance-test
    description: |
      Run gcorecloud acceptance test on rocky branch
    vars:
      global_env:
        OS_BRANCH: stable/rocky

- job:
    name: gcorecloud-acceptance-test-queens
    parent: gcorecloud-acceptance-test
    description: |
      Run gcorecloud acceptance test on queens branch
    vars:
      global_env:
        OS_BRANCH: stable/queens

- job:
    name: gcorecloud-acceptance-test-pike
    parent: gcorecloud-acceptance-test
    description: |
      Run gcorecloud acceptance test on pike branch
    vars:
      global_env:
        OS_BRANCH: stable/pike

- job:
    name: gcorecloud-acceptance-test-ocata
    parent: gcorecloud-acceptance-test
    description: |
      Run gcorecloud acceptance test on ocata branch
    vars:
      global_env:
        OS_BRANCH: stable/ocata

- job:
    name: gcorecloud-acceptance-test-newton
    parent: gcorecloud-acceptance-test
    description: |
      Run gcorecloud acceptance test on newton branch
    vars:
      global_env:
        OS_BRANCH: stable/newton

- project:
    name: gcorecloud/gcorecloud
    check:
      jobs:
        - gcorecloud-unittest
        - gcorecloud-acceptance-test
        - gcorecloud-acceptance-test-ironic
    recheck-newton:
      jobs:
        - gcorecloud-acceptance-test-newton
    recheck-ocata:
      jobs:
        - gcorecloud-acceptance-test-ocata
    recheck-pike:
      jobs:
        - gcorecloud-acceptance-test-pike
    recheck-queens:
      jobs:
        - gcorecloud-acceptance-test-queens
    recheck-rocky:
      jobs:
        - gcorecloud-acceptance-test-rocky
    recheck-stein:
      jobs:
        - gcorecloud-acceptance-test-stein
